// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Psychologicaly.Repository.Models;

public partial class Appointment
{
    public int Id { get; set; }

    public int? ProfessorId { get; set; }

    public int? UserId { get; set; }

    public string Title { get; set; }

    public DateTime? Date { get; set; }

    public string LinkMeet { get; set; }

    public string Status { get; set; }

    public bool? IsBooked { get; set; }

    public int? Star { get; set; }

    public string Comment { get; set; }

    public string Note { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual User User { get; set; }
}