// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Psychologicaly.Repository.Models;

public partial class AppointmentReport
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? AppointmentId { get; set; }

    public int? Star { get; set; }

    public string Description { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual User User { get; set; }
}