// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Psychologicaly.Repository.Models;

public partial class User
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string EmployeeCode { get; set; }

    public int RoleId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ApplicationCode { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AppointmentReport> AppointmentReports { get; set; } = new List<AppointmentReport>();

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
}